services:

  spark-master:
    build: .
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    env_file:
      - .env_master
    environment:
      - SPARK_LOCAL_IP=spark-master

  spark-worker-a:
    build: .
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    env_file:
      - .env_worker
    environment:
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

  spark-worker-b:
    build: .
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    env_file:
      - .env_worker
    environment:
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

  spark-worker-c:
    build: .
    ports:
      - "9093:8080"
      - "7003:7000"
    depends_on:
      - spark-master
    env_file:
      - .env_worker
    environment:
      - SPARK_LOCAL_IP=spark-worker-c
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

  spark-worker-d:
    build: .
    ports:
      - "9094:8080"
      - "7004:7000"
    depends_on:
      - spark-master
    env_file:
      - .env_worker
    environment:
      - SPARK_LOCAL_IP=spark-worker-d
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
